# Code generated by ambient-sdk-generator from proto — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/platform-api-server/components/ambient-api-server/proto/ambient/v1/sessions.proto
# Proto SHA256: 62d9b56b5a74fc6d5a54e6a05010a5c03fe185f90228cf45dacbace2f8c53872
# Generated: 2026-03-10T02:34:42Z

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Iterator, Optional

import grpc

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SessionMessage:
    id: str
    session_id: str
    seq: int
    event_type: str
    payload: str
    created_at: Optional[datetime]

    @classmethod
    def _from_proto(cls, pb: object) -> SessionMessage:
        ts = getattr(pb, "created_at", None)
        created_at: Optional[datetime] = None
        if ts is not None:
            try:
                created_at = datetime.fromtimestamp(
                    ts.seconds + ts.nanos / 1e9, tz=timezone.utc
                )
            except Exception:
                pass
        return cls(
            id=getattr(pb, "id", ""),
            session_id=getattr(pb, "session_id", ""),
            seq=getattr(pb, "seq", 0),
            event_type=getattr(pb, "event_type", ""),
            payload=getattr(pb, "payload", ""),
            created_at=created_at,
        )


class SessionMessagesAPI:
    """gRPC client wrapper for SessionService message RPCs."""

    _PUSH_METHOD = "/ambient.v1.SessionService/PushSessionMessage"
    _WATCH_METHOD = "/ambient.v1.SessionService/WatchSessionMessages"

    def __init__(self, channel: grpc.Channel, token: str = "") -> None:
        self._metadata = [("authorization", f"Bearer {token}")] if token else []
        self._push_rpc = channel.unary_unary(
            self._PUSH_METHOD,
            request_serializer=_PushRequest.SerializeToString,
            response_deserializer=_SessionMessageProto.FromString,
        )
        self._watch_rpc = channel.unary_stream(
            self._WATCH_METHOD,
            request_serializer=_WatchRequest.SerializeToString,
            response_deserializer=_SessionMessageProto.FromString,
        )

    def push(
        self,
        session_id: str,
        event_type: str,
        payload: str,
        *,
        timeout: float = 5.0,
    ) -> Optional[SessionMessage]:
        """Push a single message for a session. Fire-and-forget safe — logs and
        returns None on any transport error rather than raising."""
        payload_preview = payload[:120] + "..." if len(payload) > 120 else payload
        logger.info(
            "[GRPC PUSH→] session=%s event_type=%s payload_len=%d preview=%r",
            session_id,
            event_type,
            len(payload),
            payload_preview,
        )
        try:
            req = _PushRequest()
            req.session_id = session_id
            req.event_type = event_type
            req.payload = payload
            pb = self._push_rpc(req, timeout=timeout, metadata=self._metadata)
            result = SessionMessage._from_proto(pb)
            logger.info(
                "[GRPC PUSH→] OK session=%s event_type=%s seq=%d",
                session_id,
                event_type,
                result.seq,
            )
            return result
        except grpc.RpcError as exc:
            logger.warning(
                "[GRPC PUSH→] FAILED PushSessionMessage RPC (session=%s event=%s): %s",
                session_id,
                event_type,
                exc,
            )
            return None
        except Exception as exc:
            logger.warning(
                "[GRPC PUSH→] FAILED PushSessionMessage unexpected error (session=%s): %s",
                session_id,
                exc,
            )
            return None

    def watch(
        self,
        session_id: str,
        *,
        after_seq: int = 0,
        timeout: Optional[float] = None,
    ) -> Iterator[SessionMessage]:
        """Stream messages for a session starting after after_seq."""
        logger.info(
            "[GRPC WATCH←] Starting WatchSessionMessages: session=%s after_seq=%d",
            session_id,
            after_seq,
        )
        req = _WatchRequest()
        req.session_id = session_id
        req.after_seq = after_seq
        stream = self._watch_rpc(req, timeout=timeout, metadata=self._metadata)
        msg_count = 0
        for pb in stream:
            msg = SessionMessage._from_proto(pb)
            msg_count += 1
            payload_preview = (
                msg.payload[:80] + "..." if len(msg.payload) > 80 else msg.payload
            )
            logger.info(
                "[GRPC WATCH←] Message #%d received: session=%s seq=%d event_type=%s payload_len=%d preview=%r",
                msg_count,
                msg.session_id,
                msg.seq,
                msg.event_type,
                len(msg.payload),
                payload_preview,
            )
            yield msg
        logger.info(
            "[GRPC WATCH←] Stream ended: session=%s total_messages=%d",
            session_id,
            msg_count,
        )


# ---------------------------------------------------------------------------
# Minimal inline proto message classes (no generated _pb2 dependency).
# These use the protobuf runtime's message factory directly.
# ---------------------------------------------------------------------------



def _encode_string(field_number: int, value: str) -> bytes:
    encoded = value.encode("utf-8")
    tag = (field_number << 3) | 2
    return _varint(tag) + _varint(len(encoded)) + encoded


def _encode_int64(field_number: int, value: int) -> bytes:
    if value == 0:
        return b""
    tag = (field_number << 3) | 0
    return _varint(tag) + _varint(value)


def _varint(value: int) -> bytes:
    bits = value & 0x7F
    value >>= 7
    result = b""
    while value:
        result += bytes([0x80 | bits])
        bits = value & 0x7F
        value >>= 7
    result += bytes([bits])
    return result


def _decode_string(data: bytes, pos: int) -> tuple[str, int]:
    length, pos = _decode_varint(data, pos)
    return data[pos : pos + length].decode("utf-8", errors="replace"), pos + length


def _decode_varint(data: bytes, pos: int) -> tuple[int, int]:
    result = 0
    shift = 0
    while True:
        b = data[pos]
        pos += 1
        result |= (b & 0x7F) << shift
        if not (b & 0x80):
            return result, pos
        shift += 7


class _PushRequest:
    def __init__(self) -> None:
        self.session_id: str = ""
        self.event_type: str = ""
        self.payload: str = ""

    def SerializeToString(self) -> bytes:
        out = b""
        if self.session_id:
            out += _encode_string(1, self.session_id)
        if self.event_type:
            out += _encode_string(2, self.event_type)
        if self.payload:
            out += _encode_string(3, self.payload)
        return out


class _WatchRequest:
    def __init__(self) -> None:
        self.session_id: str = ""
        self.after_seq: int = 0

    def SerializeToString(self) -> bytes:
        out = b""
        if self.session_id:
            out += _encode_string(1, self.session_id)
        if self.after_seq:
            out += _encode_int64(2, self.after_seq)
        return out


class _SessionMessageProto:
    __slots__ = ("id", "session_id", "seq", "event_type", "payload", "created_at")

    def __init__(self) -> None:
        self.id: str = ""
        self.session_id: str = ""
        self.seq: int = 0
        self.event_type: str = ""
        self.payload: str = ""
        self.created_at: Optional[object] = None

    @classmethod
    def FromString(cls, data: bytes) -> _SessionMessageProto:
        msg = cls()
        pos = 0
        while pos < len(data):
            tag_varint, pos = _decode_varint(data, pos)
            field_number = tag_varint >> 3
            wire_type = tag_varint & 0x7
            if wire_type == 2:
                length, pos = _decode_varint(data, pos)
                value_bytes = data[pos : pos + length]
                pos += length
                if field_number == 1:
                    msg.id = value_bytes.decode("utf-8", errors="replace")
                elif field_number == 2:
                    msg.session_id = value_bytes.decode("utf-8", errors="replace")
                elif field_number == 4:
                    msg.event_type = value_bytes.decode("utf-8", errors="replace")
                elif field_number == 5:
                    msg.payload = value_bytes.decode("utf-8", errors="replace")
                elif field_number == 6:
                    msg.created_at = _parse_timestamp(value_bytes)
            elif wire_type == 0:
                value, pos = _decode_varint(data, pos)
                if field_number == 3:
                    msg.seq = value
            else:
                break
        return msg


class _TimestampLike:
    __slots__ = ("seconds", "nanos")

    def __init__(self, seconds: int, nanos: int) -> None:
        self.seconds = seconds
        self.nanos = nanos


def _parse_timestamp(data: bytes) -> Optional[_TimestampLike]:
    seconds = 0
    nanos = 0
    pos = 0
    while pos < len(data):
        tag_varint, pos = _decode_varint(data, pos)
        field_number = tag_varint >> 3
        wire_type = tag_varint & 0x7
        if wire_type == 0:
            value, pos = _decode_varint(data, pos)
            if field_number == 1:
                seconds = value
            elif field_number == 2:
                nanos = value
        else:
            break
    return _TimestampLike(seconds, nanos)
