// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 47119590c5b99c8ae2cf4280c6cd43829ffd283a58c334f22ff8aedc01851068
// Generated: 2026-02-26T15:57:52Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProjectSettingsAPI struct {
	client *Client
}

func (c *Client) ProjectSettings() *ProjectSettingsAPI {
	return &ProjectSettingsAPI{client: c}
}

func (a *ProjectSettingsAPI) Create(ctx context.Context, resource *types.ProjectSettings) (*types.ProjectSettings, error) {
	return a.CreateForProject(ctx, resource, "")
}

func (a *ProjectSettingsAPI) CreateForProject(ctx context.Context, resource *types.ProjectSettings, project string) (*types.ProjectSettings, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal project_settings: %w", err)
	}
	var result types.ProjectSettings
	if err := a.client.doForProject(ctx, http.MethodPost, "/project_settings", body, http.StatusCreated, &result, project); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectSettingsAPI) Get(ctx context.Context, id string) (*types.ProjectSettings, error) {
	var result types.ProjectSettings
	if err := a.client.do(ctx, http.MethodGet, "/project_settings/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectSettingsAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ProjectSettingsList, error) {
	return a.ListForProject(ctx, opts, "")
}

func (a *ProjectSettingsAPI) ListForProject(ctx context.Context, opts *types.ListOptions, project string) (*types.ProjectSettingsList, error) {
	var result types.ProjectSettingsList
	if err := a.client.doWithQueryForProject(ctx, http.MethodGet, "/project_settings", nil, http.StatusOK, &result, opts, project); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ProjectSettingsAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.ProjectSettings, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.ProjectSettings
	if err := a.client.do(ctx, http.MethodPatch, "/project_settings/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectSettingsAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/project_settings/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ProjectSettingsAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ProjectSettings] {
	return NewIterator(func(page int) (*types.ProjectSettingsList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
