// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 47119590c5b99c8ae2cf4280c6cd43829ffd283a58c334f22ff8aedc01851068
// Generated: 2026-02-26T15:57:52Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionAPI struct {
	client *Client
}

func (c *Client) Sessions() *SessionAPI {
	return &SessionAPI{client: c}
}

func (a *SessionAPI) Create(ctx context.Context, resource *types.Session) (*types.Session, error) {
	return a.CreateForProject(ctx, resource, "")
}

func (a *SessionAPI) CreateForProject(ctx context.Context, resource *types.Session, project string) (*types.Session, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal session: %w", err)
	}
	var result types.Session
	if err := a.client.doForProject(ctx, http.MethodPost, "/sessions", body, http.StatusCreated, &result, project); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Get(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodGet, "/sessions/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SessionList, error) {
	return a.ListForProject(ctx, opts, "")
}

func (a *SessionAPI) ListForProject(ctx context.Context, opts *types.ListOptions, project string) (*types.SessionList, error) {
	var result types.SessionList
	if err := a.client.doWithQueryForProject(ctx, http.MethodGet, "/sessions", nil, http.StatusOK, &result, opts, project); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *SessionAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Session, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPatch, "/sessions/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) UpdateStatus(ctx context.Context, id string, patch map[string]any) (*types.Session, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal status patch: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPatch, "/sessions/"+url.PathEscape(id)+"/status", body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Start(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions/"+url.PathEscape(id)+"/start", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Stop(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions/"+url.PathEscape(id)+"/stop", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Session] {
	return NewIterator(func(page int) (*types.SessionList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
